/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main */

#ifndef _Included_main
#define _Included_main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main
 * Method:    FindFeatures
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_main_FindFeatures
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
